### ISSUE TITLE
How to reproduce the result of target extraction?

### ISSUE THREAD

**Issue by huhk-sysu** [huminghao16/SpanABSA#1]
![image](https://user-images.githubusercontent.com/14769033/60940596-a2572300-a30e-11e9-8269-c2f25e4ffdc5.png)

I want to reproduce the result above. Here's what I have done:
1. clone the repository
2. set up environments (I've set BERT_DIR as my path to **BERT_LARGE**)
3. run the following command as in ReadMe:
 ```bash
    python -m absa.run_extract_span \
  --vocab_file $BERT_DIR/vocab.txt \
  --bert_config_file $BERT_DIR/bert_config.json \
  --init_checkpoint $BERT_DIR/pytorch_model.bin \
  --do_train \
  --do_predict \
  --data_dir $DATA_DIR \
  --train_file rest_total_train.txt \
  --predict_file rest_total_test.txt \
  --train_batch_size 32 \
  --output_dir out/extract/01
 ```

But finally I got a F1 of **73~74** on REST, which is much lower than the one reported in   the paper. 

I noticed the default value of `logit_threshold` is 7.5, and I also tried setting it to 12 (comes from the instructions of the Pipelined method in ReadMe) but the score is even lower.

Is there anything wrong? How can I obtain a high score like the one in the paper? Thank you!

**Comment by huminghao16** [comment]
Which version of BERT_LARGE have you used? The uncased one or the cased one? Notice that we use the uncased version by default. Also, you can tune the logit_threshold by yourself to see if performance can be improved.

**Comment by huhk-sysu** [comment]
> Which version of BERT_LARGE have you used? The uncased one or the cased one? Notice that we use the uncased version by default. Also, you can tune the logit_threshold by yourself to see if performance can be improved.

Thanks for your response. I'm using the **bert-large-uncased** provided by the [pytorch-pretrained-BERT](https://github.com/huggingface/pytorch-pretrained-BERT).

I fotgot to mention that I have used FP16 training. After disabling it (in this case, `gradient_accumulation_steps` is set to 2 since my GPU memory is not big enough), the model obtain a F1 score of **79.50** when the `logit_threshold` is set to 7.5. I mannually tuned it and finally get a score of **81.97** when the `logit_threshold` is set to 10.0, which is closed to the score in the paper.
