### ISSUE TITLE
how to set parameter K and M?

### ISSUE THREAD

**Issue by xilinniao123** [huminghao16/SpanABSA#7]
thanks for sharing! how to choose hyper parameter K " the maximum number of proposed targets"and M"top-M indices"??
just set K as the maximum number of targets in every sentences in  given corpus???

**Comment by xilinniao123** [comment]
感觉这两个参数 K 和 M 非常关键，如果设置不好 准确率和召回率都会非常受影响，请您多多指教

**Comment by huminghao16** [comment]
K和M的设置请参考论文，K默认为10，M默认为20
