### ISSUE TITLE
failed downloading bert_base_uncased.zip 

### ISSUE THREAD

**Issue by flyangovoyang** [huminghao16/SpanABSA#9]
It crashed several times when trying to download bert_base_uncased.zip from google drive. Where does it come from? Is there any other official website which has access to this file? Looking forward to your reply.

**Comment by huminghao16** [comment]
Our codes are modified based on pytorch-transformers, you can download
pre-trained BERT model from  https://github.com/huggingface/transformers.

flyangovoyang <notifications@github.com> 于2020年7月1日周三 下午2:18写道：

**Comment by flyangovoyang** [comment]
got it! Thanks~
